name = "chickenroad-app-com-es"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=chickenroad-app.com.es"
HMAC_KEY = "988423a1f4a6028f5bd8c74804a92b4ffc95a5003eeac3bddb55166b09d92d16"
COOKIE_NAME = "ro4"
PLAY_PATH = "start-now"
BUTTON_ID = "p911f04c338322d2e15d6caa6c71adbc2"
GATE_SALT = "326a485b341dbb29"
